export const routes = {
  HOME: '/',
  MENU: '/mon-an',
  RESERVATION: '/dat-ban',
  ORDERMENU: '/dat-mon',
  ABOUTUS: '/ve-chung-toi',
  SIGNIN: '/dang-nhap',
  SIGNUP: '/dang-ki',
  COMMIT: '/cam-ket-cua-chung-toi',
  OPERATING_POLICY: '/chinh-sach-hoat-dong',
  POLICIES_REGULATIONS: '/chinh-sach-va-quy-dinh',
  BOOKING_GUIDE: '/huong-dan-dat-ban',
  CONTACT_INSTRUCTIONS: '/huong-dan-lien-he',
  ORDER_TRACKING: '/theo-doi-dat-ban',
  MANAGEREQUEST: '/admin/manage-request',
  DASHBOARD: '/admin/dashboard',
  MANAGEFOOD: '/admin/manage-food',
  DETAILPAGE: '/detail-dish/:id',
  getDetailPage: (id) => `/detail-dish/${id}`,
}
